### ISSUE TITLE
Problems about failing to compile cython file when I install trm

### ISSUE THREAD

**Issue by PeterParkerPeng** [StuartLittlefair/pyclurve#8]
I clone pylcurve repository and successfully install it under the directory of pylcurve. When I run the scripts "lcmcmc.py" in Jupyter  notebook, the errors come with tips " no module name trm".

So I download "trm-roche" repository from User "tomrsh"  who is the author of LCURVE. When I get into directory which  trm is  located, and run "pip install -e."  Errors show blow(it's too long ,just show a part of it):
 
      trm/roche/_roche.pyx:728:11: undeclared name not builtin: roche_xl3
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              q (float): mass ratio = M2/M1
              spin (float): ratio of spin/orbital of primary
          """
          assert q > 0, "roche.xl11: q <= 0"
          assert 0 < spin <= 1, "roche.xl11: spin <= 0 or spin > 1"
          return roche_xl11(q,spin)
                 ^
      ------------------------------------------------------------
      
      trm/roche/_roche.pyx:739:11: undeclared name not builtin: roche_xl11
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              q (float): mass ratio = M2/M1
              spin (float): ratio of spin/orbital of secondary
          """
          assert q > 0, "roche.xl12: q <= 0"
          assert 0 < spin <= 1, "roche.xl12: spin <= 0 or spin > 1"
          return roche_xl12(q,spin)           ^
      ------------------------------------------------------------
      
      trm/roche/_roche.pyx:750:11: undeclared name not builtin: roche_xl12
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/jc/Documents/py-packages/trm-roche-master/setup.py", line 44, in <module>
          ext_modules=cythonize(roche),
        File "/opt/anaconda3/envs/python3.9/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/opt/anaconda3/envs/python3.9/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: trm/roche/_roche.pyx
      Compiling trm/roche/_roche.pyx because it changed.
      [1/1] Cythonizing trm/roche/_roche.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

By the way ,  I also download the "cpp-lcurve" from Tom , and set the PATH like "export TRM_SOFTWARE= (where cpp-lcurve or ptlcurve  located)" . I've tried both, but both failed.

Actually ,I'm freshman at github. So can u give me a detailed Installation tutorials  of pylcurve?  The errors may be  caused by requirements(packages version may be too high?) , or some processes  I failed to do correctly. I don't know,hh
 
Thank u!

**Comment by StuartLittlefair** [comment]
Hi, sorry for the slow reply. Installation is actually very tricky. 

pylcurve is just a wrapper for a C++ program (https://github.com/trmrsh/cpp-lcurve). This will have to be installed, along with it's C++ dependencies first
